on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}

jobs:
  deploy:
    name: Build, Push to ECR and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_REPO_URI }}

    - name: Build, tag, and push image to ECR
      run: |
        docker build -t $ECR_REPO_URI:latest ./MvcDockerApp
        docker push $ECR_REPO_URI:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster mvc-cluster \
          --service mvc-service \
          --force-new-deployment
